project:
  type: website
  output-dir: docs

website:
  title: "XXX My Name XXX"
  navbar:
    pinned: true
    left:
      - text: "About"  
        file: about.qmd
      - text: "Projects"
        file: projects.qmd
    right:
      - icon: github
        href: https://github.com/
    page-navigation: true

format:
  html:
    theme: [litera, styles.scss]
    css: styles.css
    toc: true

editor: visual

